// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8P5z3bTSUawlLmuTHVQ--Cc9Qj3Vn3f0',
    appId: '1:196845643492:web:988dd0ae106bf1ca242ef1',
    messagingSenderId: '196845643492',
    projectId: 'poojaapp-7fc98',
    authDomain: 'poojaapp-7fc98.firebaseapp.com',
    storageBucket: 'poojaapp-7fc98.appspot.com',
    measurementId: 'G-BHYL5J0K0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPduOKd5-8cwx7mgCdjOahvRNSGStcnjA',
    appId: '1:196845643492:android:2a2f81957781aa97242ef1',
    messagingSenderId: '196845643492',
    projectId: 'poojaapp-7fc98',
    storageBucket: 'poojaapp-7fc98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW5e3Q2tvm9CmLWczINy60tMnJ-A46Zlk',
    appId: '1:196845643492:ios:a3b4b285ed063e85242ef1',
    messagingSenderId: '196845643492',
    projectId: 'poojaapp-7fc98',
    storageBucket: 'poojaapp-7fc98.appspot.com',
    iosClientId: '196845643492-uugpbqa1t8i8ne5sgvuj1offofl44srl.apps.googleusercontent.com',
    iosBundleId: 'com.example.poojagoodieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW5e3Q2tvm9CmLWczINy60tMnJ-A46Zlk',
    appId: '1:196845643492:ios:a3b4b285ed063e85242ef1',
    messagingSenderId: '196845643492',
    projectId: 'poojaapp-7fc98',
    storageBucket: 'poojaapp-7fc98.appspot.com',
    iosClientId: '196845643492-uugpbqa1t8i8ne5sgvuj1offofl44srl.apps.googleusercontent.com',
    iosBundleId: 'com.example.poojagoodieApp',
  );
}
